INSERT INTO `books`(`ID`, `Title`, `Author`, `Price`, `Genre`) VALUES ('1','MANJU','M T VASUDEVAN NAIR','150','PSHYCHOLOGICAL/ROMANCE');
INSERT INTO `books`( `Title`, `Author`, `Price`, `Genre`) VALUES ('AADUJEEVITHAM','VAIKOM MUHAMMED BHASHEER','210','FICTION'),('MARTHANDAVARMA','C V RAMAN PILLAI','350','HISTORY'),('A BRIEF HISTORY OF TIME','STEPHEN HAWKING','400','SCIENCE'),('THE GREAT GATSBY','F SCOTT FITZGERALD','430','CLASSIC FICTION' );
SELECT * FROM `books` WHERE Price>400;
SELECT * FROM `books` WHERE Genre in ('HISTORY','SCIENCE','FICTION');
SELECT * FROM `books` WHERE Title = 'THE GREAT GATSBY';
SELECT * FROM `books` WHERE Author <>'DAN BROWN';
